window.DEFAULT_CHANNELS = [
  {
    "preset": 1,
    "id": "WHBQTV131.us@HD",
    "callSign": "WHBQ",
    "name": "WHBQ-DT1",
    "market": "Memphis, TN",
    "network": "Local News",
    "sourceType": "Imagicomm/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg02104-imagicommcommun-whbqbreaking-ono/playlist.m3u8",
    "note": "",
    "favorite": true
  },
  {
    "id": "Create.us",
    "callSign": "CREATE",
    "name": "Create TV",
    "market": "National",
    "network": "PBS",
    "sourceType": "PBS/public",
    "url": "https://create.lls.pbs.org/index.m3u8",
    "note": "Public/educational",
    "preset": 2,
    "favorite": false
  },
  {
    "id": "FNX.us@SD",
    "callSign": "FNX",
    "name": "First Nations Experience",
    "market": "National",
    "network": "Public",
    "sourceType": "PBS/public",
    "url": "https://fnx.lls.pbs.org/index.m3u8",
    "note": "Public/educational",
    "preset": 3,
    "favorite": false
  },
  {
    "id": "World.us",
    "callSign": "WORLD",
    "name": "WORLD Channel",
    "market": "National",
    "network": "PBS",
    "sourceType": "PBS/public",
    "url": "https://world.lls.pbs.org/index.m3u8",
    "note": "Public/educational",
    "preset": 4,
    "favorite": false
  },
  {
    "preset": 5,
    "id": "WGTV83.us@SD",
    "callSign": "WGTV",
    "name": "WGTV-DT3",
    "market": "Atlanta, GA",
    "network": "PBS",
    "sourceType": "PBS",
    "url": "https://wgtvdt3.lls.pbs.org/wgtvdt3-cmaf-hls.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 6,
    "id": "WSBDT1.us@SD",
    "callSign": "WSB",
    "name": "WSB-DT1",
    "market": "Atlanta, GA",
    "network": "Local News",
    "sourceType": "Cox/local",
    "url": "https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00327-coxmediagroup-wsbbreakingnews-ono/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 7,
    "id": "KTBC71.us@HD",
    "callSign": "KTBC",
    "name": "KTBC-DT1",
    "market": "Austin, TX",
    "network": "FOX",
    "sourceType": "Fox/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-ktbc-lgus/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 8,
    "id": "WBTSCD151.us@HD",
    "callSign": "WBTS-CD1",
    "name": "WBTS-CD1",
    "market": "Boston, MA",
    "network": "NBC",
    "sourceType": "NBC/local",
    "url": "https://d368vp0qqzvkid.cloudfront.net/11603/88889713/hls/master.m3u8?ads.xumo_channelId=88889713a&ads.xumo_ifaType=&ads.xumo_providerId=3820&ads.xumo_providerName=NBCNBOS",
    "note": "",
    "favorite": false
  },
  {
    "preset": 9,
    "id": "WSOCTV91.us@HD",
    "callSign": "WSOC",
    "name": "WSOC-DT1",
    "market": "Charlotte, NC",
    "network": "Local News",
    "sourceType": "Cox/local",
    "url": "https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00327-coxmediagroup-wsocbreaking-ono/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 10,
    "id": "WMAQTV51.us@HD",
    "callSign": "NBC",
    "name": "NBC 5 Chicago Live News",
    "market": "Chicago, IL",
    "network": "NBC",
    "sourceType": "NBC/local",
    "url": "https://d368vp0qqzvkid.cloudfront.net/11603/88889704/hls/master.m3u8?ads.xumo_channelId=88889704a&ads.xumo_ifaType=&ads.xumo_providerId=3818&ads.xumo_providerName=NBCNCHI",
    "note": "",
    "favorite": false
  },
  {
    "preset": 11,
    "id": "WFLD501.us@HD",
    "callSign": "WFLD",
    "name": "WFLD-DT1",
    "market": "Chicago, IL",
    "network": "FOX",
    "sourceType": "Fox/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-wfld-lgus/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 12,
    "id": "KDFW41.us@HD",
    "callSign": "KDFW",
    "name": "KDFW-DT1",
    "market": "Dallas\u2013Fort Worth, TX",
    "network": "FOX",
    "sourceType": "Fox/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-fox4dallaskdfw-vizious/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 13,
    "id": "KXASTV51.us@HD",
    "callSign": "KXAS",
    "name": "KXAS-DT1",
    "market": "Dallas\u2013Fort Worth, TX",
    "network": "NBC",
    "sourceType": "NBC/local",
    "url": "https://d368vp0qqzvkid.cloudfront.net/11603/88889706/hls/master.m3u8?ads.xumo_channelId=88889706a&ads.xumo_ifaType=&ads.xumo_providerId=3831&ads.xumo_providerName=NBCNDAL",
    "note": "",
    "favorite": false
  },
  {
    "preset": 14,
    "id": "WHIOTV71.us@HD",
    "callSign": "WHIO",
    "name": "WHIO-DT1",
    "market": "Dayton, OH",
    "network": "Local News",
    "sourceType": "Cox/local",
    "url": "https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00327-coxmediagroup-whiobreaking-ono/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 15,
    "id": "WJBK21.us@HD",
    "callSign": "WJBK",
    "name": "WJBK-DT1",
    "market": "Detroit, MI",
    "network": "FOX",
    "sourceType": "Fox/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-fox2detroitwjbk-vizious/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 16,
    "id": "WVIT301.us@HD",
    "callSign": "WVIT",
    "name": "WVIT-DT1",
    "market": "Hartford\u2013New Haven, CT",
    "network": "NBC",
    "sourceType": "NBC/local",
    "url": "https://d368vp0qqzvkid.cloudfront.net/11603/88889707/hls/master.m3u8?ads.xumo_channelId=88889707a&ads.xumo_ifaType=&ads.xumo_providerId=3832&ads.xumo_providerName=NBCNCT",
    "note": "",
    "favorite": false
  },
  {
    "preset": 17,
    "id": "KRIV261.us@HD",
    "callSign": "KRIV",
    "name": "KRIV-DT1",
    "market": "Houston, TX",
    "network": "FOX",
    "sourceType": "Fox/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-kriv-lgus/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 18,
    "id": "WJAXTV471.us@HD",
    "callSign": "WJAX",
    "name": "WJAX-DT1",
    "market": "Jacksonville, FL",
    "network": "Local News",
    "sourceType": "Cox/local",
    "url": "https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00327-coxmediagroup-wjaxbreaking-ono/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 19,
    "id": "KTTV111.us@HD",
    "callSign": "KTTV",
    "name": "KTTV-DT1",
    "market": "Los Angeles, CA",
    "network": "FOX",
    "sourceType": "Fox/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-fox11losangeleskttv-vizious/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 20,
    "id": "WTVJ61.us@HD",
    "callSign": "WTVJ",
    "name": "WTVJ-DT1",
    "market": "Miami, FL",
    "network": "NBC",
    "sourceType": "NBC/local",
    "url": "https://nbculocallive.akamaized.net/hls/live/2037498/miami/stream1/master.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 21,
    "id": "WITI61.us@HD",
    "callSign": "WITI",
    "name": "WITI-DT1",
    "market": "Milwaukee, WI",
    "network": "FOX",
    "sourceType": "Fox/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-witi-lgus/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 22,
    "id": "KMSPDT1.us@SD",
    "callSign": "KMSP",
    "name": "KMSP-DT1",
    "market": "Minneapolis\u2013St. Paul, MN",
    "network": "FOX",
    "sourceType": "Fox/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-kmsp-lgus/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 23,
    "id": "WNBC471.us@HD",
    "callSign": "WNBC",
    "name": "WNBC-DT1",
    "market": "New York, NY",
    "network": "NBC",
    "sourceType": "NBC/local",
    "url": "https://d368vp0qqzvkid.cloudfront.net/11603/88889709/hls/master.m3u8?ads.xumo_channelId=88889709a&ads.xumo_ifaType=&ads.xumo_providerId=3816&ads.xumo_providerName=NBCNNY",
    "note": "",
    "favorite": false
  },
  {
    "preset": 24,
    "id": "WNYW51.us@HD",
    "callSign": "WNYW",
    "name": "WNYW-DT1",
    "market": "New York, NY",
    "network": "FOX",
    "sourceType": "Fox/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-wnyw-lgus/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 25,
    "id": "WCAU621.us@HD",
    "callSign": "WCAU",
    "name": "WCAU-DT1",
    "market": "Philadelphia, PA",
    "network": "NBC",
    "sourceType": "NBC/local",
    "url": "https://d368vp0qqzvkid.cloudfront.net/11603/88889705/hls/master.m3u8?ads.xumo_channelId=88889705a&ads.xumo_ifaType=&ads.xumo_providerId=3819&ads.xumo_providerName=NBCNPHI",
    "note": "",
    "favorite": false
  },
  {
    "preset": 26,
    "id": "WTXFTV291.us@HD",
    "callSign": "WTXF",
    "name": "WTXF-DT1",
    "market": "Philadelphia, PA",
    "network": "FOX",
    "sourceType": "Fox/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-fox29philadelphiawtx-vizious/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 27,
    "id": "KSAZTV101.us@HD",
    "callSign": "KSAZ",
    "name": "KSAZ-DT1",
    "market": "Phoenix, AZ",
    "network": "FOX",
    "sourceType": "Fox/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-ksaz-lgus/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 28,
    "id": "WPXI111.us@HD",
    "callSign": "WPXI",
    "name": "WPXI-DT1",
    "market": "Pittsburgh, PA",
    "network": "Local News",
    "sourceType": "Cox/local",
    "url": "https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00327-coxmediagroup-wpxibreaking-ono/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 29,
    "id": "KVIE62.us@HD",
    "callSign": "KVIE",
    "name": "KVIE-DT2",
    "market": "Sacramento, CA",
    "network": "PBS",
    "sourceType": "PBS",
    "url": "https://kviedt2.lls.pbs.org/kviedt2-hls.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 30,
    "id": "KNSD481.us@HD",
    "callSign": "NBC",
    "name": "NBC West",
    "market": "San Diego, CA",
    "network": "NBC",
    "sourceType": "NBC/local",
    "url": "https://nbculocallive.akamaized.net/hls/live/2037098/sandiego/stream1/master.m3u8",
    "note": "Not 24/7",
    "favorite": false
  },
  {
    "preset": 31,
    "id": "KNTV111.us@HD",
    "callSign": "KNTV",
    "name": "KNTV-DT1",
    "market": "San Francisco Bay Area, CA",
    "network": "NBC",
    "sourceType": "NBC/local",
    "url": "https://d368vp0qqzvkid.cloudfront.net/11603/88889711/hls/master.m3u8?ads.xumo_channelId=88889711a&ads.xumo_ifaType=&ads.xumo_providerId=3822&ads.xumo_providerName=NBCNBA",
    "note": "",
    "favorite": false
  },
  {
    "preset": 32,
    "id": "KQED92.us@HD",
    "callSign": "KQED",
    "name": "KQED-DT2",
    "market": "San Francisco Bay Area, CA",
    "network": "PBS",
    "sourceType": "PBS",
    "url": "https://kqeddt2.lls.pbs.org/kqeddt2-hls.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 33,
    "id": "KIROTV71.us@HD",
    "callSign": "KIRO",
    "name": "KIRO-DT1",
    "market": "Seattle, WA",
    "network": "Local News",
    "sourceType": "Cox/local",
    "url": "https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00327-coxmediagroup-kirobreaking-ono/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 34,
    "id": "WEDQ34.us@HD",
    "callSign": "WEDQ",
    "name": "WEDQ-DT4",
    "market": "Tampa, FL",
    "network": "PBS",
    "sourceType": "PBS",
    "url": "https://wedqdt4.lls.pbs.org/wedqdt4-hls.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 35,
    "id": "WTVT131.us@HD",
    "callSign": "WTVT",
    "name": "WTVT-DT1",
    "market": "Tampa, FL",
    "network": "FOX",
    "sourceType": "Fox/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-fox13tampabaywtvt-vizious/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 36,
    "id": "KOKITV231.us@HD",
    "callSign": "KOKI",
    "name": "KOKI-DT1",
    "market": "Tulsa, OK",
    "network": "Local News",
    "sourceType": "Imagicomm/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg02104-imagicommcommun-kokibreaking-ono/playlist.m3u8",
    "note": "",
    "favorite": false
  },
  {
    "preset": 37,
    "id": "WRCDT1.us@SD",
    "callSign": "WRC",
    "name": "WRC-DT1",
    "market": "Washington, DC",
    "network": "NBC",
    "sourceType": "NBC/local",
    "url": "https://d368vp0qqzvkid.cloudfront.net/11603/88889708/hls/master.m3u8?ads.xumo_channelId=88889708a&ads.xumo_ifaType=&ads.xumo_providerId=3830&ads.xumo_providerName=NBCNWAS",
    "note": "",
    "favorite": false
  },
  {
    "preset": 38,
    "id": "WTTG51.us@HD",
    "callSign": "WTTG",
    "name": "WTTG-DT1",
    "market": "Washington, DC",
    "network": "FOX",
    "sourceType": "Fox/local",
    "url": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-fox5dcwttg-vizious/playlist.m3u8",
    "note": "",
    "favorite": false
  }
];
